# Generated by Django 5.1.1 on 2024-09-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('diet_preference', models.CharField(choices=[('veg', 'Vegetarian'), ('vegan', 'Vegan'), ('none', 'No preference')], max_length=5)),
            ],
        ),
    ]
